-- hermes_cli/kanban/pg_schema.sql
-- Postgres DDL for the kanban board (Phase 2). Translated from
-- hermes_cli/kanban_db.py SCHEMA_SQL. Every table carries a `board` column
-- (default 'default'); board is part of each natural key.

CREATE TABLE IF NOT EXISTS tasks (
    board                TEXT    NOT NULL DEFAULT 'default',
    id                   TEXT    NOT NULL,
    title                TEXT    NOT NULL,
    body                 TEXT,
    assignee             TEXT,
    status               TEXT    NOT NULL,
    priority             INTEGER NOT NULL DEFAULT 0,
    created_by           TEXT,
    created_at           BIGINT  NOT NULL,
    started_at           BIGINT,
    completed_at         BIGINT,
    workspace_kind       TEXT    NOT NULL DEFAULT 'scratch',
    workspace_path       TEXT,
    branch_name          TEXT,
    claim_lock           TEXT,
    claim_expires        BIGINT,
    tenant               TEXT,
    result               TEXT,
    idempotency_key      TEXT,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    worker_pid           INTEGER,
    last_failure_error   TEXT,
    max_runtime_seconds  INTEGER,
    last_heartbeat_at    BIGINT,
    current_run_id       BIGINT,
    workflow_template_id TEXT,
    current_step_key     TEXT,
    skills               TEXT,
    model_override       TEXT,
    max_retries          INTEGER,
    session_id           TEXT,
    review_target_pr_head_sha TEXT,
    goal_mode            INTEGER NOT NULL DEFAULT 0,
    goal_max_turns       INTEGER,
    PRIMARY KEY (board, id)
);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee_status ON tasks(board, assignee, status);
CREATE INDEX IF NOT EXISTS idx_tasks_status          ON tasks(board, status);
CREATE INDEX IF NOT EXISTS idx_tasks_tenant          ON tasks(board, tenant);
CREATE INDEX IF NOT EXISTS idx_tasks_idempotency     ON tasks(board, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_tasks_session_id      ON tasks(board, session_id);

CREATE TABLE IF NOT EXISTS task_links (
    board         TEXT NOT NULL DEFAULT 'default',
    parent_id     TEXT NOT NULL,
    child_id      TEXT NOT NULL,
    relation_type TEXT NOT NULL DEFAULT 'dependency',
    PRIMARY KEY (board, parent_id, child_id)
);
CREATE INDEX IF NOT EXISTS idx_links_child  ON task_links(board, child_id);
CREATE INDEX IF NOT EXISTS idx_links_parent ON task_links(board, parent_id);
CREATE INDEX IF NOT EXISTS idx_links_relation_child  ON task_links(board, relation_type, child_id);
CREATE INDEX IF NOT EXISTS idx_links_relation_parent ON task_links(board, relation_type, parent_id);

CREATE TABLE IF NOT EXISTS task_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    board      TEXT   NOT NULL DEFAULT 'default',
    task_id    TEXT   NOT NULL,
    author     TEXT   NOT NULL,
    body       TEXT   NOT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_comments_task ON task_comments(board, task_id, created_at);

CREATE TABLE IF NOT EXISTS task_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    board      TEXT   NOT NULL DEFAULT 'default',
    task_id    TEXT   NOT NULL,
    run_id     BIGINT,
    kind       TEXT   NOT NULL,
    payload    JSONB,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_events_task ON task_events(board, task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_run  ON task_events(run_id, id);

CREATE TABLE IF NOT EXISTS task_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    board               TEXT   NOT NULL DEFAULT 'default',
    task_id             TEXT   NOT NULL,
    profile             TEXT,
    step_key            TEXT,
    status              TEXT   NOT NULL,
    claim_lock          TEXT,
    claim_expires       BIGINT,
    worker_pid          INTEGER,
    max_runtime_seconds INTEGER,
    last_heartbeat_at   BIGINT,
    started_at          BIGINT NOT NULL,
    ended_at            BIGINT,
    outcome             TEXT,
    summary             TEXT,
    metadata            JSONB,
    error               TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_runs_task   ON task_runs(board, task_id, started_at);
CREATE INDEX IF NOT EXISTS idx_runs_status ON task_runs(board, status);

CREATE TABLE IF NOT EXISTS kanban_notify_subs (
    board            TEXT   NOT NULL DEFAULT 'default',
    task_id          TEXT   NOT NULL,
    platform         TEXT   NOT NULL,
    chat_id          TEXT   NOT NULL,
    thread_id        TEXT   NOT NULL DEFAULT '',
    user_id          TEXT,
    notifier_profile TEXT,
    created_at       BIGINT NOT NULL,
    last_event_id    BIGINT NOT NULL DEFAULT 0,
    event_kinds      TEXT,
    include_children INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (board, task_id, platform, chat_id, thread_id)
);
CREATE INDEX IF NOT EXISTS idx_notify_task ON kanban_notify_subs(board, task_id);

CREATE TABLE IF NOT EXISTS kanban_profile_event_subs (
    board              TEXT   NOT NULL DEFAULT 'default',
    task_id            TEXT   NOT NULL,
    profile            TEXT   NOT NULL,
    name               TEXT   NOT NULL DEFAULT '',
    event_kinds        TEXT,
    include_children   INTEGER NOT NULL DEFAULT 0,
    wake_agent         INTEGER NOT NULL DEFAULT 1,
    wake_prompt        TEXT,
    created_at         BIGINT NOT NULL,
    last_event_id      BIGINT NOT NULL DEFAULT 0,
    last_wake_at       BIGINT,
    last_wake_error_at BIGINT,
    last_wake_error    TEXT,
    wake_failure_count INTEGER NOT NULL DEFAULT 0,
    enabled            INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (board, task_id, profile, name)
);
CREATE INDEX IF NOT EXISTS idx_profile_event_subs_task    ON kanban_profile_event_subs(board, task_id);
CREATE INDEX IF NOT EXISTS idx_profile_event_subs_profile ON kanban_profile_event_subs(board, profile);

CREATE TABLE IF NOT EXISTS kanban_profile_event_claims (
    board        TEXT   NOT NULL DEFAULT 'default',
    event_id     BIGINT NOT NULL,
    profile      TEXT   NOT NULL,
    name         TEXT   NOT NULL DEFAULT '',
    root_task_id TEXT   NOT NULL,
    claimed_at   BIGINT NOT NULL,
    PRIMARY KEY (board, event_id, profile, name)
);
CREATE INDEX IF NOT EXISTS idx_profile_event_claims_root
    ON kanban_profile_event_claims(board, root_task_id, claimed_at);

CREATE TABLE IF NOT EXISTS kanban_profile_wake_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    board                TEXT   NOT NULL DEFAULT 'default',
    task_id              TEXT   NOT NULL,
    profile              TEXT   NOT NULL,
    name                 TEXT   NOT NULL DEFAULT '',
    status               TEXT   NOT NULL,
    error                TEXT,
    claimed_event_cursor BIGINT NOT NULL DEFAULT 0,
    created_at           BIGINT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_profile_wake_events_task
    ON kanban_profile_wake_events(board, task_id, profile, name);

CREATE TABLE IF NOT EXISTS kanban_notifier_heartbeats (
    board            TEXT   NOT NULL DEFAULT 'default',
    notifier_id      TEXT   NOT NULL,
    board_slug       TEXT   NOT NULL,
    db_path          TEXT   NOT NULL,
    notifier_profile TEXT,
    host             TEXT   NOT NULL,
    pid              INTEGER NOT NULL,
    started_at       BIGINT NOT NULL,
    last_seen_at     BIGINT NOT NULL,
    PRIMARY KEY (board, notifier_id, board_slug, db_path)
);
CREATE INDEX IF NOT EXISTS idx_notifier_heartbeats_seen ON kanban_notifier_heartbeats(last_seen_at);

-- Idempotent additive migrations for deployments that already created tasks
-- before pg_schema.sql gained the explicit review-target column.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS review_target_pr_head_sha TEXT;
-- goal_mode / goal_max_turns adopted from upstream #35710 (2026-06-06 merge).
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS goal_mode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS goal_max_turns INTEGER;
